name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ '*' ]

jobs:
  build-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master' && !contains(github.ref, 'refs/tags')
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Build the Docker image.
      run: docker build . --file Dockerfile --tag rcosnita/cassandra-lucene-index:latest
  build-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Build the Docker image.
      run: docker build . --file Dockerfile --tag rcosnita/cassandra-lucene-index:latest
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the tagged Docker image
      run: docker push rcosnita/cassandra-lucene-index:latest

  build-release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags')
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
      with:
        submodules: recursive
        lfs: true
    - name: Get current tag name
      uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Build the Docker image for debian stretch
      run: docker build . --file Dockerfile --tag rcosnita/cassandra-lucene-index:$GIT_TAG_NAME
    - name: Build the Docker image.
      run: docker build . --file Dockerfile --tag rcosnita/wait-container:$GIT_TAG_NAME
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the tagged Docker image
      run: docker push rcosnita/cassandra-lucene-index:$GIT_TAG_NAME
